# EXAMPLE USAGE:
#
#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/
#
[pre-commit]
parallel = true
[[pre-commit.jobs]]
run = "bun --bun prettier --write --cache --ignore-unknown"
glob = "*.{js,css,scss,less,ts,jsx,vue,html,json,md,yaml}"
