module.exports = {
    apps: [
        {
            name: 'yiapi',
            instances: 4,
            script: './main.js',
            exec_mode: 'cluster',
            watch: false,
            autorestart: true,
            interpreter: 'bun',
            ignore_watch: ['node_modules', 'logs', 'data'],
            max_memory_restart: '200M',
            env: {
                NODE_ENV: 'production',
                // 项目名称
                APP_NAME: '易接口',
                APP_PORT: 3000,
                // MD5加密盐
                MD5_SALT: 'a2ccfeba-818a-51c8-b1a4-939bade73088',
                // 监听端口,
                APP_HOST: '127.0.0.1',
                // 开发管理员密码,
                DEV_PASSWORD: '123456',
                // 请求体大小,
                BODY_LIMIT: 10,
                // 参数检查,
                PARAMS_CHECK: 0,
                // 日志等级,
                LOG_EXCLUDE_FIELDS: 'password,token',
                LOG_LEVEL: 'info',
                LOG_DIR: './logs',
                LOG_TO_CONSOLE: 1,
                LOG_MAX_SIZE: 52428800, // 50MB,
                // 时区,
                TZ: 'Asia/Shanghai',
                // 跨域配置
                ALLOWED_METHODS: 'GET, POST, PUT, DELETE, OPTIONS',
                ALLOWED_HEADERS: 'Content-Type, Authorization, authorization, token',
                EXPOSE_HEADERS: 'Content-Range, X-Content-Range, Authorization, authorization, token',
                MAX_AGE: 86400,
                ALLOW_CREDENTIALS: 'true',
                // mysql 配置,
                MYSQL_ENABLE: 0,
                MYSQL_HOST: '127.0.0.1',
                MYSQL_PORT: 3306,
                MYSQL_DB: '',
                MYSQL_USER: '',
                MYSQL_PASSWORD: '',
                MYSQL_POOL_TIMEOUT: '60000',
                MYSQL_POOL_MAX: '10',
                MYSQL_DEBUG: 0,
                // redis 配置,
                REDIS_URL: 'redis://root:root@127.0.0.1:6379',
                REDIS_ENABLE: 0,
                REDIS_HOST: '127.0.0.1',
                REDIS_PORT: 6379,
                REDIS_USERNAME: '',
                REDIS_PASSWORD: '',
                REDIS_DB: 3,
                REDIS_KEY_PREFIX: '',
                // JWT 配置,
                JWT_SECRET: 'dbfaf2c3-7ade-5042-b843-eca8814714b3',
                JWT_EXPIRES_IN: '30d',
                JWT_ALGORITHM: 'HS256',
                // 邮箱配置,
                MAIL_HOST: 'smtp.qq.com',
                MAIL_PORT: 465,
                MAIL_POOL: 1,
                MAIL_SECURE: 1,
                MAIL_USER: '',
                MAIL_PASS: '',
                MAIL_SENDER: '',
                MAIL_ADDRESS: 'demo@qq.com',
                // 上传配置,
                LOCAL_DIR: '/wwwroot/static2/',
                // 微信配置,
                PAY_NOTIFY_URL: ''
            }
        }
    ]
};
